apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: tagpay-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: admin
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: NODE_ENV
              value: "development"
            - name: VITE_API_URL
              value: "http://server-service:3000"
