name: tagpay-infrastructure
description: TagPay Infrastructure as Code using Pulumi
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
      project: tagpay
      managed-by: pulumi
